CREATE TABLE `eqemu_special_abilities`(
  id        SMALLINT                                         PRIMARY KEY,
  name      VARCHAR(64)                                      NOT NULL,
  category  ENUM('offense','defense','behavior','immunity')  NOT NULL,
  details   TEXT                                             NOT NULL
);

-- DATA
INSERT INTO `eqemu_special_abilities` (id, name, category, details) VALUES
  (1, 'Summon', 'behavior', 'Summon target->NPC or NPC->target; supports cooldown [ms] and HP% threshold.'),
  (2, 'Enrage', 'defense', 'Begins at HP% threshold; ripostes incoming melee; duration and cooldown in ms.'),
  (3, 'Rampage', 'offense', 'Extra attacks on additional targets; params for proc%, target count, dmg%, flat dmg, AC ignore, crit mods.'),
  (4, 'AE Rampage', 'offense', 'Rampage that hits all in range [or N targets]; same tunables as Rampage.'),
  (5, 'Flurry', 'offense', 'Chance to add extra swings; params for proc%, added hits, dmg%, flat dmg, AC ignore, crit mods.'),
  (6, 'Triple Attack', 'offense', 'Enables three melee swings per round.'),
  (7, 'Quad Attack', 'offense', 'Enables four melee swings per round.'),
  (8, 'Dual Wield', 'offense', 'Allows off-hand weapon attack.'),
  (9, 'Bane Attack', 'offense', 'Can damage targets requiring bane-type weapons.'),
  (10, 'Magical Attack', 'offense', 'Can damage targets requiring magical weapons.'),
  (11, 'Ranged Attack', 'offense', 'Uses ranged attacks out of melee; params: min/max range, hit% mod, dmg% mod.'),
  (12, 'Slow', 'immunity', 'Immune to slow effects.'),
  (13, 'Mez', 'immunity', 'Immune to mesmerize.'),
  (14, 'Charm', 'immunity', 'Immune to charm.'),
  (15, 'Stun', 'immunity', 'Immune to stun.'),
  (16, 'Snare', 'immunity', 'Immune to snare.'),
  (17, 'Fear', 'immunity', 'Immune to fear.'),
  (18, 'Dispel', 'immunity', 'Immune to dispel effects.'),
  (19, 'Melee Damage', 'immunity', 'Immune to all melee damage.'),
  (20, 'Spells', 'immunity', 'Immune to all magic spells.'),
  (21, 'Doesn''t Flee', 'behavior', 'Will never flee at low HP.'),
  (22, 'Non-Bane Weapons', 'immunity', 'Only damaged by correct bane-type weapons.'),
  (23, 'Non-Magical Weapons', 'immunity', 'Only damaged by magical weapons.'),
  (24, 'Players Can''t Aggro', 'behavior', 'Players cannot enter its hate list.'),
  (25, 'Won''t Aggro other NPCs', 'behavior', 'Cannot be added to any hate list.'),
  (26, 'Belly Caster', 'defense', 'Blocks spells cast outside melee range ["belly cast" required].'),
  (27, 'Feign Death', 'immunity', 'Detects FD; FD players can still be aggrod/kept on hate.'),
  (28, 'Taunt', 'immunity', 'Taunt has no effect.'),
  (29, 'Tunnel Vision', 'behavior', 'Hate from non-top targets is scaled by an aggro modifier param.'),
  (30, 'Doesn''t Buff/Heal Allies', 'behavior', "Won't cast beneficial spells on same-faction allies."),
  (31, 'Pacify', 'immunity', 'Immune to pacify/lull.'),
  (32, 'Leashed', 'behavior', 'If pulled past leash distance, returns home, heals, wipes hate; param sets distance.'),
  (33, 'Tethered', 'behavior', 'Hard tether near aggro range; param sets leash distance before snap-back.'),
  (34, 'Destructible', 'behavior', 'For destructible NPC objects [deprecated]; simple on/off.'),
  (35, 'All Player Damage', 'immunity', 'Players cannot harm it by any means.'),
  (36, 'Always Flee', 'behavior', 'Will flee at low HP regardless of ally proximity.'),
  (37, 'Flee at %', 'behavior', 'Flees at specified HP%; ignores ally checks; param = HP%.'),
  (38, 'Allow Beneficial', 'behavior', 'Players may cast beneficial spells on this NPC.'),
  (39, 'Disable Melee', 'behavior', 'Cannot perform melee attacks; can still aggro.'),
  (40, 'Chase Distance', 'behavior', 'Sets max/min chase distances; optional ignore-LOS flag.'),
  (41, 'Allow Tank', 'behavior', 'Allows other NPCs to take aggro from players.'),
  (42, 'Ignore Root Aggro', 'behavior', 'While rooted, attacks hate-top, not nearest target.'),
  (43, 'Casting Resist Mod', 'offense', 'Applies a flat resist-difficulty modifier to spells cast by this NPC.'),
  (44, 'Lower Opponent Avoid', 'offense', "Reduces a client's avoidance; increases NPC hit rate."),
  (45, 'Proximity Aggro', 'behavior', 'Can add new nearby clients to hate while already in combat.'),
  (46, 'Ranged Attacks', 'immunity', 'Immune to ranged weapon damage.'),
  (47, 'Players', 'immunity', 'Immune to damage from players.'),
  (48, 'NPCs', 'immunity', 'Immune to damage from NPCs.'),
  (49, 'Player Aggro', 'immunity', 'Players cannot generate aggro on it.'),
  (50, 'NPC Aggro', 'immunity', 'NPCs cannot generate aggro on it.'),
  (51, 'Raise Avoidance', 'defense', "Increases this NPC's avoidance [all or specific skills]."),
  (52, 'Fading Memories', 'immunity', 'Immune to memory-fade/aggro-wipe effects.'),
  (53, 'Open', 'immunity', 'Immune to /open.'),
  (54, 'Assassinate', 'immunity', 'Immune to Rogue Assassinate.'),
  (55, 'Headshot', 'immunity', 'Immune to Ranger Headshot.'),
  (56, 'Bot Aggro', 'immunity', 'Bots cannot generate aggro on it.'),
  (57, 'Bots', 'immunity', 'Immune to damage from bots.');
