CREATE TABLE `eqemu_classes`(
  id            SMALLINT PRIMARY KEY,
  name          VARCHAR(64)                                                      NOT NULL,
  category      ENUM('player_class','guildmaster','merchant','banker','service') NOT NULL,
  short_name    CHAR(3)                                                          NULL
);

-- DATA
INSERT INTO `eqemu_classes` (id, name, category, short_name) VALUES
  (1, 'Warrior', 'player_class', 'WAR'),
  (2, 'Cleric', 'player_class', 'CLR'),
  (3, 'Paladin', 'player_class', 'PAL'),
  (4, 'Ranger', 'player_class', 'RNG'),
  (5, 'Shadow Knight', 'player_class', 'SHD'),
  (6, 'Druid', 'player_class', 'DRU'),
  (7, 'Monk', 'player_class', 'MON'),
  (8, 'Bard', 'player_class', 'BRD'),
  (9, 'Rogue', 'player_class', 'ROG'),
  (10, 'Shaman', 'player_class', 'SHM'),
  (11, 'Necromancer', 'player_class', 'NEC'),
  (12, 'Wizard', 'player_class', 'WIZ'),
  (13, 'Magician', 'player_class', 'MAG'),
  (14, 'Enchanter', 'player_class', 'ENC'),
  (15, 'Beastlord', 'player_class', 'BST'),
  (16, 'Berserker', 'player_class', 'BER'),
  (20, 'Warrior Guildmaster', 'guildmaster', NULL),
  (21, 'Cleric Guildmaster', 'guildmaster', NULL),
  (22, 'Paladin Guildmaster', 'guildmaster', NULL),
  (23, 'Ranger Guildmaster', 'guildmaster', NULL),
  (24, 'Shadow Knight Guildmaster', 'guildmaster', NULL),
  (25, 'Druid Guildmaster', 'guildmaster', NULL),
  (26, 'Monk Guildmaster', 'guildmaster', NULL),
  (27, 'Bard Guildmaster', 'guildmaster', NULL),
  (28, 'Rogue Guildmaster', 'guildmaster', NULL),
  (29, 'Shaman Guildmaster', 'guildmaster', NULL),
  (30, 'Necromancer Guildmaster', 'guildmaster', NULL),
  (31, 'Wizard Guildmaster', 'guildmaster', NULL),
  (32, 'Magician Guildmaster', 'guildmaster', NULL),
  (33, 'Enchanter Guildmaster', 'guildmaster', NULL),
  (34, 'Beastlord Guildmaster', 'guildmaster', NULL),
  (35, 'Berserker Guildmaster', 'guildmaster', NULL),
  (40, 'Banker', 'banker', NULL),
  (41, 'Merchant', 'merchant', NULL),
  (59, 'Discord Merchant (PVP Points)', 'merchant', NULL),
  (60, 'Adventure Recruiter', 'service', NULL),
  (61, 'Adventure Merchant', 'merchant', NULL),
  (63, 'Tribute Master', 'service', NULL),
  (64, 'Guild Tribute Master', 'service', NULL),
  (66, 'Guild Banker', 'banker', NULL),
  (67, 'Norrath''s Keeper Merchant', 'merchant', NULL),
  (68, 'Dark Reign Merchant', 'merchant', NULL),
  (69, 'Fellowship Master', 'service', NULL),
  (70, 'Alternate Currency Merchant', 'merchant', NULL),
  (71, 'Mercenary Liaison', 'service', NULL);
