CREATE TABLE `eqemu_item_types` (
  id   SMALLINT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  is_instrument TINYINT UNSIGNED NOT NULL DEFAULT 0
) COMMENT='EQ item functional types (join to items.itemtype)';

INSERT INTO `eqemu_item_types` (id, `name`, is_instrument) VALUES
  (0 ,  '1H Slashing',                  0),
  (1 ,  '2H Slashing',                  0),
  (2 ,  'Piercing',                     0),
  (3 ,  '1H Blunt',                     0),
  (4 ,  '2H Blunt',                     0),
  (5 ,  'Archery',                      0),
  (6 ,  'Crossbow',                     0),
  (7 ,  'Throwing v1',                  0),
  (8 ,  'Shield',                       0),
  (9 ,  'Spell',                        0),
  (10,  'Armor',                        0),
  (11,  'Misc',                         0),
  (12,  'Lockpicks',                    0),
  (13,  'Fist',                         0),
  (14,  'Food',                         0),
  (15,  'Drink',                        0),
  (16,  'Light',                        0),
  (17,  'Combinable',                   0),
  (18,  'Bandages',                     0),
  (19,  'Throwing v2',                  0),
  (20,  'Scroll',                       0),
  (21,  'Potion',                       0),
  (22,  'Fletched Arrow',               0),
  (23,  'Wind Instrument',              1),
  (24,  'Stringed Instrument',          1),
  (25,  'Brass Instrument',             1),
  (26,  'Percussion Instrument',        1),
  (27,  'Arrow',                        0),
  (28,  'Bolt',                         0),
  (29,  'Jewelry',                      0),
  (30,  'Skull',                        0),
  (31,  'Book',                         0),
  (32,  'Note',                         0),
  (33,  'Key v1',                       0),
  (34,  'Coin',                         0),
  (35,  '2H Piercing',                  0),
  (36,  'Fishing Pole',                 0),
  (37,  'Fishing Bait',                 0),
  (38,  'Alcohol',                      0),
  (39,  'Key v2',                       0),
  (40,  'Compass',                      0),
  (41,  'Metal Key',                    0),
  (42,  'Poison',                       0),
  (43,  'Magic Arrow',                  0),
  (44,  'Magic Bolt',                   0),
  (45,  'Hand to Hand',                 0),
  (46,  'Item Has Effect',              0),
  (47,  'Haste Item',                   0),
  (48,  'Item Has FT',                  0),
  (49,  'Item Has Focus',               0),
  (50,  'Singing Instrument',           1),
  (51,  'All Instruments',              1),
  (52,  'Charm',                        0),
  (53,  'Armor Dye',                    0),
  (54,  'Augment',                      0),
  (55,  'Augment Solvent',              0),
  (56,  'Augment Distiller',            0),
  (57,  'Alternate Ability',            0),
  (58,  'Guild Banner Kit',             0),
  (59,  'Guild Banner Modify Token',    0),
  (60,  'Cultural Armor Recipe Book',   0),
  (61,  'Cultural Weapon Recipe Book',  0),
  (62,  'Book with Spell Effect',       0),
  (63,  'Alternate Currency',           0),
  (64,  'Perfected Augment Distiller',  0),
  (65,  'Placeable',                    0),
  (66,  'Collectible',                  0),
  (67,  'Container',                    0),
  (68,  'Mount',                        0),
  (69,  'Illusion',                     0),
  (70,  'Familiar',                     0),
  (71,  'Unknown71',                    0),
  (72,  'Unknown72',                    0),
  (255, 'Unknown',                      0);
