CREATE TABLE `pok_eqemu_skills`(
  id            SMALLINT     PRIMARY KEY,
  name          VARCHAR(64)  NOT NULL,
  short_name    VARCHAR(16)  NULL,
  is_tradeskill TINYINT(1)   NOT NULL DEFAULT 0
);

-- DATA
INSERT INTO `pok_eqemu_skills` (id, name, short_name, is_tradeskill) VALUES
  (0, '1H Blunt', '1HB', 0),
  (1, '1H Slashing', '1HS', 0),
  (2, '2H Blunt', '2HB', 0),
  (3, '2H Slashing', '2HS', 0),
  (4, 'Abjuration', 'ABJ', 0),
  (5, 'Alteration', 'ALT', 0),
  (6, 'Apply Poison', 'APOI', 1),
  (7, 'Archery', 'ARCH', 0),
  (8, 'Backstab', 'BSTA', 0),
  (9, 'Bind Wound', 'BIND', 0),
  (10, 'Bash', 'BASH', 0),
  (11, 'Block', 'BLK', 0),
  (12, 'Brass Instruments', 'BRAS', 0),
  (13, 'Channeling', 'CHAN', 0),
  (14, 'Conjuration', 'CONJ', 0),
  (15, 'Defense', 'DEF', 0),
  (16, 'Disarm', 'DIS', 0),
  (17, 'Disarm Traps', 'DTRP', 0),
  (18, 'Divination', 'DIV', 0),
  (19, 'Dodge', 'DOD', 0),
  (20, 'Double Attack', 'DBL', 0),
  (21, 'Dragon Punch', 'DRAG', 0),
  (22, 'Dual Wield', 'DW', 0),
  (23, 'Eagle Strike', 'EGL', 0),
  (24, 'Evocation', 'EVO', 0),
  (25, 'Feign Death', 'FD', 0),
  (26, 'Flying Kick', 'FK', 0),
  (27, 'Forage', 'FOR', 0),
  (28, 'Hand To Hand', 'H2H', 0),
  (29, 'Hide', 'HIDE', 0),
  (30, 'Kick', 'KICK', 0),
  (31, 'Meditate', 'MED', 0),
  (32, 'Mend', 'MEND', 0),
  (33, 'Offense', 'OFF', 0),
  (34, 'Parry', 'PARR', 0),
  (35, 'Pick Lock', 'PICK', 0),
  (36, '1H Piercing', '1HP', 0),
  (37, 'Riposte', 'RIPO', 0),
  (38, 'Round Kick', 'RK', 0),
  (39, 'Safe Fall', 'SAFE', 0),
  (40, 'Sense Heading', 'SENS', 0),
  (41, 'Singing', 'SING', 0),
  (42, 'Sneak', 'SNEK', 0),
  (43, 'Specialize Abj', 'SPAB', 0),
  (44, 'Specialize Alt', 'SPAL', 0),
  (45, 'Specialize Conj', 'SPCO', 0),
  (46, 'Specialize Div', 'SPDV', 0),
  (47, 'Specialize Evo', 'SPEV', 0),
  (48, 'Pick Pockets', 'PP', 0),
  (49, 'Stringed Instruments', 'STRI', 0),
  (50, 'Swimming', 'SWIM', 0),
  (51, 'Throwing', 'THRW', 0),
  (52, 'Tiger Claw', 'TIGR', 0),
  (53, 'Tracking', 'TRAK', 0),
  (54, 'Wind Instruments', 'WIND', 0),
  (55, 'Fishing', 'FISH', 1),
  (56, 'Make Poison', 'MPOI', 1),
  (57, 'Tinkering', 'TINK', 1),
  (58, 'Research', 'RSCH', 1),
  (59, 'Alchemy', 'ALCH', 1),
  (60, 'Baking', 'BAKE', 1),
  (61, 'Tailoring', 'TAIL', 1),
  (62, 'Sense Traps', 'STRP', 0),
  (63, 'Blacksmithing', 'SMTH', 1),
  (64, 'Fletching', 'FLET', 1),
  (65, 'Brewing', 'BREW', 1),
  (66, 'Alcohol Tolerance', 'ALC', 0),
  (67, 'Begging', 'BEG', 0),
  (68, 'Jewelry Making', 'JEWL', 1),
  (69, 'Pottery', 'POTT', 1),
  (70, 'Percussion Instruments', 'PERC', 0),
  (71, 'Intimidation', 'INTI', 0),
  (72, 'Berserking', 'BRZR', 0),
  (73, 'Taunt', 'TAUNT', 0),
  (74, 'Frenzy', 'FRNZ', 0),
  (75, 'Remove Trap', 'RMTR', 0),
  (76, 'Triple Attack', 'TRPL', 0),
  (77, '2H Piercing', '2HP', 0);
