CREATE TABLE `pok_eqemu_npc_abilities`(
  id        SMALLINT                                         PRIMARY KEY,
  name      VARCHAR(64)                                      NOT NULL,
  category  ENUM('offense','defense','behavior','immunity')  NOT NULL,
  details   TEXT                                             NOT NULL
);

-- DATA
INSERT INTO `pok_eqemu_npc_abilities` (id, name, category, details) VALUES
  (1, 'Summon', 'behavior', 'Summon target->NPC or NPC->target; supports cooldown [ms] and HP% threshold.'),
  (2, 'Enrage', 'defense', 'Begins at HP% threshold; ripostes incoming melee; duration and cooldown in ms.'),
  (3, 'Rampage', 'offense', 'Extra attacks on additional targets; params for proc%, target count, dmg%, flat dmg, AC ignore, crit mods.'),
  (4, 'Area Rampage', 'offense', 'Rampage that hits all in range [or N targets]; same tunables as Rampage.'),
  (5, 'Flurry', 'offense', 'Chance to add extra swings; params for proc%, added hits, dmg%, flat dmg, AC ignore, crit mods.'),
  (6, 'Triple Attack', 'offense', 'Enables three melee swings per round.'),
  (7, 'Quad Attack', 'offense', 'Enables four melee swings per round.'),
  (8, 'Dual Wield', 'offense', 'Allows off-hand weapon attack.'),
  (9, 'Bane Attack', 'offense', 'Can damage targets requiring bane-type weapons.'),
  (10, 'Magical Attack', 'offense', 'Can damage targets requiring magical weapons.'),
  (11, 'Ranged Attack', 'offense', 'Uses ranged attacks out of melee; params: min/max range, hit% mod, dmg% mod.'),
  (12, 'Unslowable', 'immunity', 'Immune to slow effects.'),
  (13, 'Unmezable', 'immunity', 'Immune to mesmerize.'),
  (14, 'Uncharmable', 'immunity', 'Immune to charm.'),
  (15, 'Unstunable', 'immunity', 'Immune to stun.'),
  (16, 'Unsnareable', 'immunity', 'Immune to snare.'),
  (17, 'Unfearable', 'immunity', 'Immune to fear.'),
  (18, 'Immune to Dispell', 'immunity', 'Immune to dispel effects.'),
  (19, 'Immune to Melee', 'immunity', 'Immune to all melee damage.'),
  (20, 'Immune to Magic', 'immunity', 'Immune to all magic spells.'),
  (21, 'Immune to Fleeing', 'behavior', 'Will never flee at low HP.'),
  (22, 'Immune to Non-Bane Damage', 'immunity', 'Only damaged by correct bane-type weapons.'),
  (23, 'Immune to Non-Magical Damage', 'immunity', 'Only damaged by magical weapons.'),
  (24, 'Will Not Aggro', 'behavior', 'Players cannot enter its hate list.'),
  (25, 'Immune to Aggro', 'behavior', 'Cannot be added to any hate list.'),
  (26, 'Resist Ranged Spells', 'defense', 'Blocks spells cast outside melee range ["belly cast" required].'),
  (27, 'See through Feign Death', 'immunity', 'Detects FD; FD players can still be aggrod/kept on hate.'),
  (28, 'Immune to Taunt', 'immunity', 'Taunt has no effect.'),
  (29, 'Tunnel Vision', 'behavior', 'Hate from non-top targets is scaled by an aggro modifier param.'),
  (30, 'Does NOT buff/heal friends', 'behavior', "Won't cast beneficial spells on same-faction allies."),
  (31, 'Unpacifiable', 'immunity', 'Immune to pacify/lull.'),
  (32, 'Leashed', 'behavior', 'If pulled past leash distance, returns home, heals, wipes hate; param sets distance.'),
  (33, 'Tethered', 'behavior', 'Hard tether near aggro range; param sets leash distance before snap-back.'),
  (34, 'Destructible Object', 'behavior', 'For destructible NPC objects [deprecated]; simple on/off.'),
  (35, 'No Harm from Players', 'immunity', 'Players cannot harm it by any means.'),
  (36, 'Always Flee', 'behavior', 'Will flee at low HP regardless of ally proximity.'),
  (37, 'Flee Percentage', 'behavior', 'Flees at specified HP%; ignores ally checks; param = HP%.'),
  (38, 'Allow Beneficial', 'behavior', 'Players may cast beneficial spells on this NPC.'),
  (39, 'Disable Melee', 'behavior', 'Cannot perform melee attacks; can still aggro.'),
  (40, 'Chase Distance', 'behavior', 'Sets max/min chase distances; optional ignore-LOS flag.'),
  (41, 'Allow Tank', 'behavior', 'Allows other NPCs to take aggro from players.'),
  (42, 'Ignore Root Aggro', 'behavior', 'While rooted, attacks hate-top, not nearest target.'),
  (43, 'Casting Resist Diff', 'offense', 'Applies a flat resist-difficulty modifier to spells cast by this NPC.'),
  (44, 'Counter Avoid Damage', 'offense', "Reduces a client's avoidance; increases NPC hit rate."),
  (45, 'Proximity Aggro', 'behavior', 'Can add new nearby clients to hate while already in combat.'),
  (46, 'Immune Ranged Attacks', 'immunity', 'Immune to ranged weapon damage.'),
  (47, 'Immune Client Damage', 'immunity', 'Immune to damage from players.'),
  (48, 'Immune NPC Damage', 'immunity', 'Immune to damage from NPCs.'),
  (49, 'Immune Client Aggro', 'immunity', 'Players cannot generate aggro on it.'),
  (50, 'Immune NPC Aggro', 'immunity', 'NPCs cannot generate aggro on it.'),
  (51, 'Modify Avoid Damage', 'defense', "Increases this NPC's avoidance [all or specific skills]."),
  (52, 'Immune Fading Memories', 'immunity', 'Immune to memory-fade/aggro-wipe effects.'),
  (53, 'Immune to Open', 'immunity', 'Immune to /open.'),
  (54, 'Immune to Assassinate', 'immunity', 'Immune to Rogue Assassinate.'),
  (55, 'Immune to Headshot', 'immunity', 'Immune to Ranger Headshot.'),
  (56, 'Immune to Bot Aggro', 'immunity', 'Bots cannot generate aggro on it.'),
  (57, 'Immune to Bot Damage', 'immunity', 'Immune to damage from bots.');
