CREATE TABLE `pok_eqemu_container_types`(
  id          SMALLINT PRIMARY KEY,
  name        VARCHAR(64)  NOT NULL
);

INSERT INTO `pok_eqemu_container_types` (id, name) VALUES
  (1,  'General'),
  (2,  'Quiver'),
  (3,  'General'),
  (4,  'General'),
  (5,  'General'),
  (6,  'General'),
  (7,  'General'),
  (8,  'General'),
  (9,  'Alchemy Container'),
  (10, 'Toolbox'),
  (11, 'Books'),
  (12, 'Mortar and Pestle'),
  (13, 'Quest Related'),
  (14, 'Mixing Bowl'),
  (15, 'Spit'),
  (16, 'Sewing Kit'),
  (17, 'Forge'),
  (18, 'Fletching Kit'),
  (19, 'Brewing'),
  (20, 'Jeweler''s Kit'),
  (21, 'Pottery'),
  (22, 'New Tanaan Kiln'),
  (24, 'Wizard Research'),
  (25, 'Magician Research'),
  (26, 'Necromancer Research'),
  (27, 'Enchanter Research'),
  (29, 'Concordance of Research'),
  (30, 'Quest Combine container'),
  (46, 'Tackle Box'),
  (51, 'Trader''s Satchel'),
  (53, 'Augmentation Sealer'),
  (54, 'Cooking'),
  (55, '2H Slashing'),
  (56, 'Piercing'),
  (57, '1H Blunt'),
  (58, '2H Blunt'),
  (59, 'Archery');
