SELECT
  c.id                          AS character_,
  c.account_id                  AS character_,
  c.title                       AS character_,
  c.name                        AS character_,
  c.last_name                   AS character_,
  c.suffix                      AS character_,

  c.level                       AS character_,
  c.level2                      AS character_highest_level,
  c.race                        AS character_,
  c.class                       AS character_,
  c.deity                       AS character_,
  
  c.cur_hp                      AS character_,
  c.mana                        AS character_,
  c.endurance                   AS character_,
  c.str                         AS character_,
  c.sta                         AS character_,
  c.cha                         AS character_,
  c.dex                         AS character_,
  c.int                         AS character_,
  c.agi                         AS character_,
  c.wis                         AS character_,
  c.points                      AS character_,
  c.extra_haste                 AS character_,

  c.intoxication                AS character_,
  c.toxicity                    AS character_,
  c.hunger_level                AS character_,
  c.thirst_level                AS character_,
  c.air_remaining               AS character_,

  c.ingame                      AS character_,
  c.RestTimer                   AS character_,

  c.zone_id                     AS character_location_zone_id,
  c.zone_instance               AS character_location_zone_instance,
  c.y                           AS character_location_y,
  c.x                           AS character_location_x,
  c.z                           AS character_location_z,
  c.heading                     AS character_location_heading,

  c.exp                         AS character_,
  c.aa_exp                      AS character_,
  c.group_leadership_exp        AS character_,
  c.raid_leadership_exp         AS character_,

  c.exp_enabled                 AS character_,
  c.aa_points                   AS character_,
  c.aa_points_spent             AS character_,
  c.aa_points_spent_old         AS character_,
  c.aa_points_old               AS character_,
  c.group_leadership_points     AS character_,
  c.raid_leadership_points      AS character_,
  c.e_percent_to_aa             AS character_,
  c.leadership_exp_on           AS character_,

  c.ability_time_seconds        AS character_,
  c.ability_number              AS character_,
  c.ability_time_minutes        AS character_,
  c.ability_time_hours          AS character_,
  c.zone_change_count           AS character_,
  c.ability_up                  AS character_,
  c.mailkey                     AS character_,
  c.xtargets                    AS character_,
  c.e_aa_effects                AS character_,
  c.e_expended_aa_spent         AS character_,

  c.autosplit_enabled           AS character_,
  c.ldon_points_guk             AS character_,
  c.ldon_points_mir             AS character_,
  c.ldon_points_mmc             AS character_,
  c.ldon_points_ruj             AS character_,
  c.ldon_points_tak             AS character_,
  c.ldon_points_available       AS character_,
  c.tribute_points              AS character_,
  c.tribute_active              AS character_,
  c.tribute_time_remaining      AS character_,
  c.career_tribute_points       AS character_,
  
  c.group_auto_consent          AS character_,
  c.raid_auto_consent           AS character_,
  c.guild_auto_consent          AS character_,
  c.anon                        AS character_,
  c.gm                          AS character_,
  c.lfp                         AS character_,
  c.lfg                         AS character_,

  c.gender                      AS character_,
  c.face                        AS character_,
  c.show_helm                   AS character_,
  c.hair_color                  AS character_,
  c.hair_style                  AS character_,
  c.beard                       AS character_,
  c.beard_color                 AS character_,
  c.eye_color_1                 AS character_,
  c.eye_color_2                 AS character_,
  c.drakkin_heritage            AS character_,
  c.drakkin_tattoo              AS character_,
  c.drakkin_details             AS character_,
  c.illusion_block              AS character_,
  
  c.pvp_status                  AS character_,
  c.pvp_kills                   AS character_,
  c.pvp_deaths                  AS character_,
  c.pvp_current_points          AS character_,
  c.pvp_career_points           AS character_,
  c.pvp_best_kill_streak        AS character_,
  c.pvp_worst_death_streak      AS character_,
  c.pvp_current_kill_streak     AS character_,
  c.pvp2                        AS character_,
  c.pvp_type                    AS character_,

  c.birthday                    AS character_,
  c.last_login                  AS character_,
  c.time_played                 AS character_,
  c.deleted_at                  AS character_,
  c.first_login                 AS character_,
  c.e_last_invsnapshot          AS character_
FROM character_data c

/* Test restrictions, remove when done testing*/
LIMIT 1;
